name: Deploy Backend (POC)

on:
  push:
    branches:
      - POC

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Backend to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd Hackathon_Project_Enigma_BE
            git checkout POC
            git pull origin POC

            docker stop enigma-backend || true
            docker rm enigma-backend || true

            docker build -t enigma-be .
            docker run -d \
              --name enigma-backend \
              -p 80:8000 \
              -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
              enigma-be
